# Generated by Django 4.2.5 on 2023-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday_at',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
