# Generated by Django 4.2.5 on 2023-11-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
